version: '3.9'

services:
  db:
    container_name: postgres-next
    image: postgres:18.0
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PORT: ${POSTGRES_PORT}
    volumes:
      - ./postgres:/var/lib/postgresql

  pgadmin:
    container_name: pgadmin-next
    image: dpage/pgadmin4:9.9.0
    ports:
      - 8080:80
    environment:
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
    volumes:
      - ./pgadmin:/var/lib/pgadmin
    depends_on:
      - db
